layout_spectrum: 0.7469509
color:
  saturation: 0.06263553
  lightness: 0.5370668
  brandStrength: 0.6057348
  brandColors:
    - '#030404'
    - '#E1EAFC'
    - '#919191'
    - '#655B4B'
    - '#FFA255'
  rhythmicContrast: 0.05194114
typography_spectrum: 0.1863799
name: Romää the Grid
